-- Baseline schema. Postgres-flavored SQL that also runs on H2 (PostgreSQL mode).
-- Every schema change from here on gets its own V2__, V3__, ... file.
CREATE TABLE users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255),
    title     VARCHAR(255),
    team      VARCHAR(255),
    bio       VARCHAR(1000),
    photo_url VARCHAR(255)
);
